@startuml
set separator none
title Bacumen - Dynamic

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

AddElementTag("Container,Database", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")

AddBoundaryTag("Software System", $bgColor="#ffffff", $borderColor="#0b4884", $fontColor="#0b4884", $shadowing="", $borderStyle="Solid", $borderThickness="1")

System_Boundary("Bacumen_boundary", "Bacumen", $tags="Software System") {
  AddBoundaryTag("API", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_1, "API", $tags="API") {
    Container(Bacumen.APIService, "API Service", $techn="", $descr="Server", $tags="Container", $link="")
  }

  AddBoundaryTag("Dashboard", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_2, "Dashboard", $tags="Dashboard") {
    Container(Bacumen.VisualizationPanel, "VisualizationPanel", $techn="", $descr="Server", $tags="Container", $link="")
  }

}

System_Boundary("EdgeComputingPlatform_boundary", "Edge Computing Platform", $tags="Software System") {
  Container(EdgeComputingPlatform.HubDevice, "Hub Device", $techn="", $descr="Edge Hub to integrate and orchastrate data from the sensor network.", $tags="Container", $link="")
}

System_Boundary("Int2DataFabricPlatform_boundary", "Int2 Data Fabric Platform", $tags="Software System") {
  AddBoundaryTag("Backend Services", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_3, "Backend Services", $tags="Backend Services") {
      AddBoundaryTag("Backend Services/API Gateway Service", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
      Boundary(group_4, "API Gateway Service", $tags="Backend Services/API Gateway Service") {
        Container(Int2DataFabricPlatform.APIService, "API Service", $techn="", $descr="API Gateway Managed Service", $tags="Container", $link="")
      }

      AddBoundaryTag("Backend Services/Data Pipeline Service", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
      Boundary(group_5, "Data Pipeline Service", $tags="Backend Services/Data Pipeline Service") {
        Container(Int2DataFabricPlatform.StreamPipelineBackend, "Stream Pipeline Backend", $techn="Container: Zenoh Backend S3", $descr="Subscribe data to store", $tags="Container", $link="")
        ContainerDb(Int2DataFabricPlatform.StreamPipelineStorage, "Stream Pipeline Storage", $techn="AWS S3", $descr="Raw data storage", $tags="Container,Database", $link="")
      }

  }

}

Rel(EdgeComputingPlatform.HubDevice, Int2DataFabricPlatform.StreamPipelineBackend, "1. Data Ingestion", $techn="", $tags="Relationship", $link="")
Rel(Int2DataFabricPlatform.StreamPipelineBackend, Int2DataFabricPlatform.StreamPipelineStorage, "2. store", $techn="", $tags="Relationship", $link="")
Rel(Bacumen.APIService, Int2DataFabricPlatform.APIService, "3. Request to access to specific dataource", $techn="", $tags="Relationship", $link="")
Rel(Bacumen.VisualizationPanel, Int2DataFabricPlatform.StreamPipelineStorage, "4. connect", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml