@startuml
set separator none
title Bacumen - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

AddElementTag("Software System", $bgColor="#1168bd", $borderColor="#0b4884", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")

AddBoundaryTag("Software System", $bgColor="#ffffff", $borderColor="#0b4884", $fontColor="#0b4884", $shadowing="", $borderStyle="Solid", $borderThickness="1")

WithoutPropertyHeader()
AddProperty("Owner","intellectus.software")
System(Int2Fabric, "Int2 Fabric", $descr="Autonomous Bigdata Platform has been powerd by Intellectu's Data Fabric Platform which contains the data virtualizations to manage data and the semantic search to discover and the data pipelines to make automated workflows.", $tags="Software System", $link="")

System_Boundary("Bacumen_boundary", "Bacumen", $tags="Software System") {
  AddBoundaryTag("API", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_1, "API", $tags="API") {
    Container(Bacumen.APIService, "API Service", $techn="", $descr="Server", $tags="Container", $link="")
  }

  AddBoundaryTag("Dashboard", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
  Boundary(group_2, "Dashboard", $tags="Dashboard") {
    Container(Bacumen.VisualizationPanel, "VisualizationPanel", $techn="", $descr="Server", $tags="Container", $link="")
  }

}

Rel(Bacumen.VisualizationPanel, Int2Fabric, "", $techn="", $tags="Relationship", $link="")
Rel(Int2Fabric, Bacumen.APIService, "", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml