@startuml
set separator none
title Deployment - Integration

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Deployment>

AddElementTag("Element", $bgColor="#ffffff", $borderColor="#888888", $fontColor="#000000", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container,Database,Hycon", $bgColor="#ffd470", $borderColor="#b2944e", $fontColor="#4a4a4a", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container,Hycon", $bgColor="#ffd470", $borderColor="#b2944e", $fontColor="#4a4a4a", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container,Database", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")

Deployment_Node(Integration.HyconDataPipeline, "Hycon Data Pipeline", $type="", $descr="", $tags="Element", $link="") {
  ContainerDb(Integration.HyconDataPipeline.AutonomousDataStore_1, "Autonomous Data Store", $techn="", $descr="Database", $tags="Container,Database,Hycon", $link="")
  ContainerDb(Integration.HyconDataPipeline.MetadataStore_1, "Metadata Store", $techn="", $descr="Database", $tags="Container,Database,Hycon", $link="")
  Container(Integration.HyconDataPipeline.MetadataExtraction_1, "Metadata Extraction", $techn="", $descr="API Server", $tags="Container,Hycon", $link="")
  Container(Integration.HyconDataPipeline.Anontmization_1, "Anontmization", $techn="", $descr="API Server", $tags="Container,Hycon", $link="")
  Container(Integration.HyconDataPipeline.Visualization_1, "Visualization", $techn="", $descr="API Server", $tags="Container,Hycon", $link="")
}

Deployment_Node(Integration.IntellectusDataFabric, "Intellectus Data Fabric", $type="", $descr="", $tags="Element", $link="") {
  Deployment_Node(Integration.IntellectusDataFabric.KnowledgeService, "Knowledge Service", $type="", $descr="", $tags="Element", $link="") {
    Container(Integration.IntellectusDataFabric.KnowledgeService.KnowledgeGraphApp_1, "Knowledge Graph App", $techn="Container: Serverless Java or Typescript Application", $descr="Provides", $tags="Container", $link="")
    ContainerDb(Integration.IntellectusDataFabric.KnowledgeService.KnowledgeGraphDatabase_1, "Knowledge Graph Database", $techn="", $descr="DB: Neo4j or AWS Neptune", $tags="Container,Database", $link="")
  }

  Deployment_Node(Integration.IntellectusDataFabric.APIGatewayService, "API Gateway Service", $type="", $descr="", $tags="Element", $link="") {
    Container(Integration.IntellectusDataFabric.APIGatewayService.APIService_1, "API Service", $techn="", $descr="API Gateway Managed Service", $tags="Container", $link="")
  }

  Container(Integration.IntellectusDataFabric.DataSourceGateway_1, "Data Source Gateway", $techn="Container: Java Application", $descr="Manage data pipeline between distburited data source and Data Fabric in secure.", $tags="Container", $link="")
  Deployment_Node(Integration.IntellectusDataFabric.MetadataService, "Metadata Service", $type="", $descr="", $tags="Element", $link="") {
    Container(Integration.IntellectusDataFabric.MetadataService.MetadataApp_1, "Metadata App", $techn="", $descr="Active Metadata", $tags="Container", $link="")
    ContainerDb(Integration.IntellectusDataFabric.MetadataService.MetadataDatabase_1, "Metadata Database", $techn="", $descr="DB: AWS Aurora Postgrsql", $tags="Container,Database", $link="")
  }

}

Rel(Integration.IntellectusDataFabric.KnowledgeService.KnowledgeGraphApp_1, Integration.IntellectusDataFabric.MetadataService.MetadataApp_1, "", $techn="", $tags="Relationship", $link="")
Rel(Integration.IntellectusDataFabric.KnowledgeService.KnowledgeGraphApp_1, Integration.IntellectusDataFabric.KnowledgeService.KnowledgeGraphDatabase_1, "build Local Knowledge Graph", $techn="", $tags="Relationship", $link="")
Rel(Integration.IntellectusDataFabric.APIGatewayService.APIService_1, Integration.IntellectusDataFabric.MetadataService.MetadataApp_1, "", $techn="", $tags="Relationship", $link="")
Rel(Integration.IntellectusDataFabric.APIGatewayService.APIService_1, Integration.IntellectusDataFabric.KnowledgeService.KnowledgeGraphApp_1, "", $techn="", $tags="Relationship", $link="")
Rel(Integration.HyconDataPipeline.MetadataExtraction_1, Integration.HyconDataPipeline.AutonomousDataStore_1, "Extract metadata(by file)", $techn="", $tags="Relationship", $link="")
Rel(Integration.HyconDataPipeline.MetadataExtraction_1, Integration.HyconDataPipeline.Anontmization_1, "Anonymization", $techn="", $tags="Relationship", $link="")
Rel(Integration.HyconDataPipeline.Visualization_1, Integration.HyconDataPipeline.MetadataStore_1, "Load Data", $techn="", $tags="Relationship", $link="")
Rel(Integration.HyconDataPipeline.Anontmization_1, Integration.HyconDataPipeline.Visualization_1, "Processing for Visualization", $techn="", $tags="Relationship", $link="")
Rel(Integration.IntellectusDataFabric.DataSourceGateway_1, Integration.HyconDataPipeline.AutonomousDataStore_1, "", $techn="", $tags="Relationship", $link="")
Rel(Integration.IntellectusDataFabric.DataSourceGateway_1, Integration.HyconDataPipeline.MetadataStore_1, "", $techn="", $tags="Relationship", $link="")
Rel(Integration.IntellectusDataFabric.MetadataService.MetadataApp_1, Integration.IntellectusDataFabric.DataSourceGateway_1, "", $techn="", $tags="Relationship", $link="")
Rel(Integration.IntellectusDataFabric.MetadataService.MetadataApp_1, Integration.IntellectusDataFabric.MetadataService.MetadataDatabase_1, "", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml