@startuml
set separator none
title Knowledge Graph App - Dynamic

left to right direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

AddElementTag("Element", $bgColor="#dddddd", $borderColor="#9a9a9a", $fontColor="#000000", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container,Database", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container,Web Browser", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")
AddElementTag("Container", $bgColor="#438dd5", $borderColor="#2e6295", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")

AddBoundaryTag("Container", $bgColor="#ffffff", $borderColor="#2e6295", $fontColor="#2e6295", $shadowing="", $borderStyle="Solid", $borderThickness="1")

Container_Boundary("Int2DataFabricPlatform.KnowledgeGraphApp_boundary", "Knowledge Graph App", $tags="Container") {
  Component(Int2DataFabricPlatform.KnowledgeGraphApp.KnowledgeSlipboxApiProvider, "Knowledge Slipbox Api Provider", $techn="", $descr="Knowledge Graph", $tags="Element", $link="")
}

Container_Boundary("Int2DataFabricPlatform.MetadataApp_boundary", "Metadata App", $tags="Container") {
  Component(Int2DataFabricPlatform.MetadataApp.MetaGin, "Meta Gin", $techn="Component: Spring bean", $descr="Metadata Analyzer", $tags="Element", $link="")
  Component(Int2DataFabricPlatform.MetadataApp.FabricDataCatalog, "Fabric Data Catalog", $techn="", $descr="Component: Spring bean", $tags="Element", $link="")
}

ContainerDb(Int2DataFabricPlatform.KnowledgeGraphDatabase, "Knowledge Graph Database", $techn="", $descr="DB: Neo4j or AWS Neptune", $tags="Container,Database", $link="")
Container(Int2DataFabricPlatform.WebApplication, "Web Application", $techn="", $descr="Serverless nextjs", $tags="Container,Web Browser", $link="")
Container(Int2DataFabricPlatform.APIService, "API Service", $techn="", $descr="API Gateway Managed Service", $tags="Container", $link="")

Rel(Int2DataFabricPlatform.MetadataApp.MetaGin, Int2DataFabricPlatform.MetadataApp.FabricDataCatalog, "1. fetch", $techn="", $tags="Relationship", $link="")
Rel(Int2DataFabricPlatform.KnowledgeGraphApp.KnowledgeSlipboxApiProvider, Int2DataFabricPlatform.KnowledgeGraphDatabase, "2. fetch", $techn="", $tags="Relationship", $link="")
Rel(Int2DataFabricPlatform.APIService, Int2DataFabricPlatform.KnowledgeGraphApp.KnowledgeSlipboxApiProvider, "3. ", $techn="", $tags="Relationship", $link="")
Rel(Int2DataFabricPlatform.APIService, Int2DataFabricPlatform.MetadataApp.MetaGin, "4. ", $techn="", $tags="Relationship", $link="")
Rel(Int2DataFabricPlatform.WebApplication, Int2DataFabricPlatform.APIService, "5. use as Knowledge Catalog", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml