@startuml
set separator none
title System Landscape

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddElementTag("Software System", $bgColor="#1168bd", $borderColor="#0b4884", $fontColor="#ffffff", $sprite="", $shadowing="", $borderStyle="Solid", $borderThickness="1")

AddRelTag("Relationship", $textColor="#707070", $lineColor="#707070", $lineStyle = "")

AddBoundaryTag("Bacumen", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_1, "Bacumen", $tags="Bacumen") {
  WithoutPropertyHeader()
  AddProperty("Owner","intellectus.software")
  System(Bacumen, "Bacumen", $descr="Business Acumen provides a visualization to act for the business sucess.", $tags="Software System", $link="")
}

AddBoundaryTag("EdgePlatform", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_2, "EdgePlatform", $tags="EdgePlatform") {
  WithoutPropertyHeader()
  AddProperty("Owner","intellectus.software")
  System(EdgeComputingPlatform, "Edge Computing Platform", $descr="Edge Computing Platform", $tags="Software System", $link="")
}

AddBoundaryTag("Int2Fabric", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="Dashed", $borderThickness="1")
Boundary(group_3, "Int2Fabric", $tags="Int2Fabric") {
  WithoutPropertyHeader()
  AddProperty("Owner","intellectus.software")
  System(Int2Fabric, "Int2 Fabric", $descr="Autonomous Bigdata Platform has been powerd by Intellectu's Data Fabric Platform which contains the data virtualizations to manage data and the semantic search to discover and the data pipelines to make automated workflows.", $tags="Software System", $link="")
}


Rel(Bacumen, Int2Fabric, "", $techn="", $tags="Relationship", $link="")
Rel(EdgeComputingPlatform, Int2Fabric, "", $techn="", $tags="Relationship", $link="")
Rel(Int2Fabric, Bacumen, "", $techn="", $tags="Relationship", $link="")

SHOW_LEGEND(true)
@enduml